In [1]:
from Test_Data_Loader import Dataset_Activity
import numpy as np
import treescope

In [10]:
print("=== TESTING DATASET_ACTIVITY WITH COVARIATES ===")

# Test with your session file
dataset = Dataset_Activity(
    root_path="../DATA",
    data_path="session_61f260e7-b5d3-4865-a577-bcfc53fda8a8.h5",
    flag='train',
    size=[48,16,16]
)

print(f"\nDataset length: {len(dataset)}")
print(f"Feature names: {dataset.feature_names}")

# Test a few samples
i = 800
seq_x, seq_y, seq_x_mark, seq_y_mark = dataset[i]

print(f"\nSample {i}:")
print(f"  seq_x shape: {seq_x.shape}")
print(f"  seq_y shape: {seq_y.shape}")  
print(f"  seq_x_mark shape: {seq_x_mark.shape}")
print(f"  seq_y_mark shape: {seq_y_mark.shape}")
print(f"  Wheel velocity range: {seq_x_mark[:, 0].min():.3f} to {seq_x_mark[:, 0].max():.3f}")
print(f"  Stimulus activity: {np.sum(seq_x_mark[:, 1:10].sum(axis=1) > 0)} samples with stimulus")

print("\n✓ Dataset_Activity successfully loads and provides covariate data!")

=== TESTING DATASET_ACTIVITY WITH COVARIATES ===
Loaded preprocessed data: (19081, 6903)
Loaded covariate matrix: (19081, 11)
Original neurons: 7673, Processed neurons: 6903
Data range: 0.000 to 1.000
Covariate features: ['wheel_velocity', 'stimulus_catch_trial', 'stimulus_left_100pct', 'stimulus_left_25pct', 'stimulus_left_12.5pct', 'stimulus_left_6.25pct', 'stimulus_right_100pct', 'stimulus_right_25pct', 'stimulus_right_12.5pct', 'stimulus_right_6.25pct', 'trial_phase']
Selected top 5000 neurons out of 6903 preprocessed neurons
Final dataset shape: (13356, 5000)
Final covariate shape: (13356, 11)
Final data statistics - Mean: 0.366, Std: 0.184

Dataset length: 13293
Feature names: ['wheel_velocity', 'stimulus_catch_trial', 'stimulus_left_100pct', 'stimulus_left_25pct', 'stimulus_left_12.5pct', 'stimulus_left_6.25pct', 'stimulus_right_100pct', 'stimulus_right_25pct', 'stimulus_right_12.5pct', 'stimulus_right_6.25pct', 'trial_phase']
Index: 800
Input sequence end (s_end): 848 (steps 80

In [11]:
treescope.basic_interactive_setup(autovisualize_arrays=True)

In [12]:
dataset.feature_names

['wheel_velocity',
 'stimulus_catch_trial',
 'stimulus_left_100pct',
 'stimulus_left_25pct',
 'stimulus_left_12.5pct',
 'stimulus_left_6.25pct',
 'stimulus_right_100pct',
 'stimulus_right_25pct',
 'stimulus_right_12.5pct',
 'stimulus_right_6.25pct',
 'trial_phase']

In [13]:
seq_x

array([[0.03851357, 0.20001294, 0.2767173 , ..., 0.04374486, 0.03081449,
        0.27158737],
       [0.03853282, 0.11996091, 0.13911499, ..., 0.06407376, 0.04508758,
        0.2671907 ],
       [0.15406327, 0.31452075, 0.36714232, ..., 0.07291362, 0.03109727,
        0.2054951 ],
       ...,
       [0.22061715, 0.32094458, 0.39472374, ..., 0.2867207 , 0.17696993,
        0.31444585],
       [0.12091029, 0.1429594 , 0.24803118, ..., 0.2591783 , 0.13955355,
        0.29691517],
       [0.27925456, 0.22883217, 0.18298417, ..., 0.24846084, 0.10236396,
        0.2600069 ]], shape=(48, 5000), dtype=float32)

In [14]:
seq_x_mark.T

array([[-0.03065728,  0.02090241, -0.01016896, -0.03381756, -0.13184772,
        -0.20539838, -0.08476406, -0.07787008, -0.00698303,  0.00139088,
        -0.02011095,  0.04274531, -0.0363264 ,  0.03625152, -0.01532596,
         0.3627668 ,  1.1782993 ,  0.7119119 ,  0.1442442 ,  0.3218723 ,
         0.06277845, -0.03154143,  0.02721775, -0.02714594,  0.02921108,
        -0.0283229 ,  0.02303446, -0.01640422,  0.0017254 ,  0.01595951,
        -0.03779865,  0.05618794, -0.64163834, -0.79976606,  0.00500626,
        -0.05154505, -0.06761569, -0.13602398,  0.02221897,  0.45823932,
        -0.2826897 ,  0.03367461,  0.28876802, -0.52140045, -0.06599747,
         0.13257319, -0.1555466 ,  0.04922605],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.

In [15]:
seq_y

array([[0.42462638, 0.47072095, 0.3398719 , ..., 0.68255764, 0.0213006 ,
        0.03105405],
       [0.381042  , 0.67769265, 0.35193056, ..., 0.7510205 , 0.08139076,
        0.04903045],
       [0.3941271 , 0.60081774, 0.26645193, ..., 0.6614729 , 0.12436832,
        0.14255525],
       ...,
       [0.32341877, 0.24904984, 0.33970895, ..., 0.84819335, 0.00972007,
        0.02580553],
       [0.42024228, 0.2388593 , 0.1267371 , ..., 0.7745768 , 0.05015037,
        0.05348036],
       [0.19508648, 0.3258852 , 0.17358808, ..., 0.6515969 , 0.07473974,
        0.04181879]], shape=(32, 5000), dtype=float32)

In [16]:
seq_y_mark.T

array([[-0.64163834, -0.79976606,  0.00500626, -0.05154505, -0.06761569,
        -0.13602398,  0.02221897,  0.45823932, -0.2826897 ,  0.03367461,
         0.28876802, -0.52140045, -0.06599747,  0.13257319, -0.1555466 ,
         0.04922605, -0.0099038 , -0.01516518,  0.02480821, -0.01918726,
         0.01034757, -0.00318223, -0.00551388,  0.00426165, -0.00210417,
        -0.01904685,  0.0098625 , -0.02857013,  0.03630551, -0.05163615,
        -0.53489184, -0.4476031 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.       